# util/load_data.py, DATASET_DICT
dataset_name: "TDE-v2" 

# framework/prompt_generator.py
chat_mode: "example"
code_mode: "inst_example"

# vLLM for FT model
vllm_model: "./models/llama3_lora_sft"
vllm_cfg:
  base_url: "http://localhost:8000/v1"
  api_key: "token-abc123"
  temperature: 0.2

# OPENAI
openai_model: "gpt-4o-mini"
openai_cfg:
  api_key: "sk-xxx"
  temperature: 0.2
