# Path
dataset_dir: "data/raw"
instruction_dir: "data/instruction"
code_dir: "exp/code"
result_dir: "exp/result"

# OPENAI
llm:
  model_name: "xxx"
  api_key: "sk-xxx"
  temp_python_file: "src/temp_solve.py"
